# Generated by Django 5.0.2 on 2024-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='date',
            new_name='mdate',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='memail',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='mname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='mphone',
        ),
    ]
