# Generated by Django 5.0.2 on 2024-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_contact_memail_alter_contact_mphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mdate',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='des',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='mphone',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='memail',
        ),
        migrations.AddField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
